version: '3'

services:
  frontend:    
    build:
      context: ./RandomChatFrontend      
    ports:
      - "3000:3000"
    volumes:
      - ./RandomChatFrontend:/app
      - react_app:/app/dist
    depends_on:
      - backend
      - redis
    networks:
      - RandomChatNetwork
   
  backend:
    build:
      context: ./RandomChat
    ports:
      - "8000:8000"
    volumes:
      - ./RandomChat:/code
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
    networks:
      - RandomChatNetwork
   
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - RandomChatNetwork

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - react_app:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - RandomChatNetwork
    command: ["nginx", "-g", "daemon off;"]
    
networks:
  RandomChatNetwork:
    driver: bridge  

volumes:
  react_app:
