version: '3'

services:
  frontend:
    build:
      context: ./RandomChatFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - RandomChatNetwork

  backend:
    build:
      context: ./RandomChat
      dockerfile: Dockerfile
    volumes:
      - ./RandomChat:/code
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - RandomChatNetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - RandomChatNetwork

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - RandomChatNetwork

networks:
  RandomChatNetwork:
    driver: bridge
