version: '3'

services:
  frontend:
    build:
      context: ./RandomChatFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - RandomChatNetwork

  backend:
    build:
      context: ./RandomChat
      dockerfile: Dockerfile
    volumes:
      - ./RandomChat:/code
    env_file:
      - .env.production
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - RandomChatNetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - RandomChatNetwork

networks:
  RandomChatNetwork:
    driver: bridge
